src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import signup
from blog import settings


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('posts.urls')),
                  path('trap/', include('traps.urls')),
                  path('compte/nouveau/', signup, name="signup"),
                  path("compte/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # permet de lier nos url des media au image. sans quoi l'mage ne peut pas sortir.

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('<str:slug>', BlogPostDetail.as_view(), name="post"),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name="edit"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),

]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>

    <section id="blog">
        {% block content %}
        {% endblock  %}
    </section>

</body>
</html>