src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import signup
from blog import settings


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('posts.urls')),
                  path('trap/', include('traps.urls')),
                  path('compte/nouveau/', signup, name="signup"),
                  path("compte/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # permet de lier nos url des media au image. sans quoi l'mage ne peut pas sortir.

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('<str:slug>', BlogPostDetail.as_view(), name="post"),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name="edit"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),

]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")# verbose_name permet de donner un label qui doit s'afficher dans les formulaires
    slug = models.CharField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(
            self):  # cette fonction permet d'envoyer le titre de l'article comme l'element a afficher par defaut quand on appelle un article
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author if self.author else "L'auteur inconnu"
        # ici self.author renvoi automatiquement le username(ici l'email) de l'utilisateur, à cause du fait
        # que la fonction __str__ defini dans la class AbstractBaseUser de django du quel notre model
        # utilisateur personalisé herite, pointe sur username_field comme l'element à afficher par defaut.
        #alors que dans notre model personalisé, ce champs(username_fiels) est pointé sur l'attribu "email".
        #ce n'est donc pas la peine de dire "return self.author.email" car la fonction __str__ pointe deja sur ce champs(email)
        # "return self.author" suffit donc.

    def get_absolute_url(self):
        return reverse('posts:home')
        # cette fonction get_absolute_url permet de rediriger vers une urls donnée, elle est implicitement appélé
        # lors de la création d'une instance à partir dun formulaire
        # la fonction reverse permet de recuperer une url à partir de son nom et du space name(app_name) qui sont definis
        # dans urls.py de l'application.

src/posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import request
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from posts.models import BlogPost


class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    # ici on a pas besoin d'indiquer quel template il doit afficher les article.
    # par defaut, les ListView cherche un template dont le nom est composé du nom de notre application et celui
    # de notre model suivi de "_list.html" comme ceci: posts/blogpost_list. il suffit donc de creer ce fichier html
    # dans un dossier portant le nom de l'app, et le tout dans un dossier appélé "templates".

    def get_queryset(
            self):  # ici on verifie si le user est connecté pour lui envoyer tous les article, sinon seulement ceux publiés.
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        else:
            return queryset.filter(published=True)
        # cette fonction est celle qui est automatiquement et implicitement appélée par ListView pour recuperer les donnees de la base
        # il s'agit ici donc d'une surcharge de cette fonction.


@method_decorator(login_required, name="dispatch")
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title', 'content', ]
    # la variable "form" utilisée dans le template blogpost_create est implicite, c'est à dire qu'il est automatiquement
    # envoyée par le CreateView sur le template, on pourra donc y acceder.


@method_decorator(login_required, name="dispatch")
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_edit.html"
    fields = ['title', 'content', 'published']


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"


@method_decorator(login_required, name="dispatch")
class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = "post"
    success_url = reverse_lazy("posts:home")  # permet de rediriger vers la home page après la suppression.
    # cette classe DeleteView cherche automatiquement un template dont le nom est composé du nom du model(pas de l'application) et
    # le suffix "_confirm_delete.html", comme ceci "blogpost_confirm_delete.html", il suffi donc de créer ce tempate
    # dans un dossier portant le nom de l'application le tout dans le dossier "templates" de l'application.
    # sinon on aurait tout simplement pu indiquer le nom de template à chercher comme on l'a fait dans la CreateView.

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title></title>
{% endblock %}


{% block content %}

    <form method="POST">
      {% csrf_token %}
      <p>Etes vous sûr de vouloir supprimer " <strong><i>{{ post.title }}</i> </strong> " </p>
      <input type="submit" value="Oui, Supprimer" class="btn btn-delete">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du site</title>
{% endblock %}

{% block content %}

    <h1> Ajouter un article</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Créer" class="btn btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>post.title</title>
{% endblock %}

{% block content %}
    <article class="post-detail">
       <h1>{{ post.title}}</h1>
        {% if post.thumbnail  %}
        <img src="{{ post.thumbnail.url }}" alt="l'image de l'article">
        {% endif%}
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>
{% endblock %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du site</title>
{% endblock %}

{% block content %}

    <h1> Editer l'article</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Modifier" class="btn btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du site</title>
{% endblock %}

{% block content %}

    <h1> Le blog de Sacko</h1>
    {% for post in posts %}
        <article>

          <div class="post-title">
               <h2>{{ post.title}}</h2>

                {% if request.user.is_authenticated %}
                    <div>
                            <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                            <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                    </div>
                {% endif %}
          </div>

            <h5 class="post-author">Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }} </h5>
            <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>

            <form action="{% url 'posts:post' slug=post.slug %}">
              <button class="btn btn-submit">Lire l'article</button>
            </form>

        </article>
    {% endfor %}

{% endblock %}